### ISSUE TITLE
Frame label is not shown on the exported image

### ISSUE THREAD

**Issue by stenalpjolly** [tldraw/tldraw-beta#10]
Steps to recreate
1. Create a new frame
2. Edit frame label
3. Add shapes inside frame
4. Export as image

Expectation: Frame label should be shown 
Current: Frame label is not shown

**Comment by steveruizok** [comment]
Thanks for the issue!

**Comment by TodePond** [comment]
A fix for this should be coming out this week!

**Comment by TodePond** [comment]
This should be working now! 🎉
