### ISSUE TITLE
File system

### ISSUE THREAD

**Issue by chipallen2** [tldraw/tldraw-beta#16]
The new tldraw beta doesn't have the File > Open button to reopen a file I saved to my computer as .tldraw. Where did that go?

**Comment by alex-kim-dev** [comment]
I think it's not implemented yet. I can't even save a file, `ctrl + s` saves html instead.

**Comment by chipallen2** [comment]
As long as it's not being dropped as a feature. I use that heavily. I save files to dropbox and share with the team. 
Then others can reopen it from same shared dropbox.

Kind of a simple way to have some shared drawings.

**Comment by TodePond** [comment]
Hey we're working on this at the moment - we're not dropping it :)

**Comment by mikkelking** [comment]
+1 for this. I like the improved interface, but being able to save to file is critical. 
It's also not clear how sharing works, where does it share too? Is it possible to get the source of the file somehow?

**Comment by TodePond** [comment]
An update: We're hoping to push out a very basic way of importing/exporting projects this week.

> It's also not clear how sharing works, where does it share too? Is it possible to get the source of the file somehow?

After sharing a project, other people can join and edit it if you give them the QR code, or the project link. There's currently an internal ticket open to make this process clearer - thanks for your feedback on that!
<img width="240" alt="Screenshot 2023-01-31 at 09 28 32" src="https://user-images.githubusercontent.com/15892272/215721431-3490cc76-bc14-45ec-9108-b0e7b9317a3b.png">

**Comment by SPYFF** [comment]
Thanks for the update!

**Comment by TodePond** [comment]
Hi again, we had to push back our file-system features to a later release. We're still working on its first version, and trying to get it out soon!

**Comment by TodePond** [comment]
It's finally here!!!

And next week we're hoping to allow you to upload files from the old version too :)
