### ISSUE TITLE
Missing translations: zh-CN

### ISSUE THREAD

**Issue by wemsx** [tldraw/tldraw-beta#17]
I can change to any other language except Chinese-Simplified.
If there's no Chinese version of translation now , maybe I can help with the i18n work.

**Comment by wemsx** [comment]
It seems that the file 'zh-cn.json' is missing , here's one I made myself(based on zh-tw.json) , wish it would help.
![](https://raw.githubusercontent.com/wemsx/wemsx-static/master/2022/12/upgit_20221212_1670831150.png)
[https://raw.githubusercontent.com/wemsx/wemsx-static/master/2022/12/upgit_20221212_1670831211.json](https://raw.githubusercontent.com/wemsx/wemsx-static/master/2022/12/upgit_20221212_1670831211.json)

**Comment by wemsx** [comment]
It seems that the file 'zh-cn.json' is missing , here's one I made myself(based on zh-tw.json) , wish it would help.
![](https://raw.githubusercontent.com/wemsx/wemsx-static/master/2022/12/upgit_20221212_1670831150.png)
[https://raw.githubusercontent.com/wemsx/wemsx-static/master/2022/12/upgit_20221212_1670831211.json](https://raw.githubusercontent.com/wemsx/wemsx-static/master/2022/12/upgit_20221212_1670831211.json)

**Comment by TodePond** [comment]
Hey thanks for bringing this up - we're still working on completing all our translations at the moment, so that's very helpful!

**Comment by TodePond** [comment]
Thanks again for this - the updated translations are now live!
