### ISSUE TITLE
[Feature] Double-click to add text to shape

### ISSUE THREAD

**Issue by alex-radulescu-b1** [tldraw/tldraw-beta#23]
Hi,

I just discovered `tldraw` and it is awesome! 
Congrats on all the work.
I would like to propose a feature to make it easier to diagram things.

### Scenario
- Using `tldraw` as a quick diagraming tool for online meetings
- Need to be able to quickly put up shapes, add some text to them and draw lines from shape-to-shape

### Suggestion
- When a user `clicks` on a shape in the sidebar, then clicks on the canvas, the shape would be created (current behaviour)
- When the user `double-clicks` on an existing shape on the canvas, the user could add text to the shape (new behaviour) instead of adding more of the same shape of a default size
- [Alternative/Add-on] Add `Edit` \ `Add Text` as a quick option alongside `Duplicate` when right-clicking on a shape
<img width="804" alt="tldraw" src="https://user-images.githubusercontent.com/60082210/207607947-2efe00ee-321b-4b4d-99a7-ca5744814717.png">

- When a user `clicks & drag` then the selected shape would be created at the expected `user-dragged` size

Hope this will be useful, and if you have any questions, let me know.

Cheers,
Alex R

**Comment by alex-kim-dev** [comment]
This workflow could be sped up with a few shortcuts:

- tools shortcuts, e.g. `V` for select, `R` for rectangle
- `enter` on a selected shape to add text
- `esc` to exit typing and select the shape again
- `ctrl + D` to duplicate a selected shape

**Comment by TodePond** [comment]
Hi, thanks! Just so I understand, do you mean something different to the current 'label' feature? You can add text labels to the middle of shapes by double-clicking them. (When a shape has no fill, you need to double-click its border).

Is this the same as what you are imagining, or do you have something different in mind? :)

![Kapture 2022-12-15 at 10 49 18](https://user-images.githubusercontent.com/15892272/207840639-ff8b7c8d-86b8-41fc-94de-e7e7248a458f.gif)

**Comment by alexradulescu** [comment]
Hi @TodePond,

That looks about right.
It makes sense to have to `double-click` on the border if there is no fill, but in using the beta it doesn't seem to behave as in the video. Please see the video attached.


https://user-images.githubusercontent.com/3583196/207848730-5e059e30-fcc1-4df3-8f32-3d2aa3b46e34.mov


Also in the video, by the looks of it, after `double-clicking` to edit, it stays in edit/move mode.
My suggestion was:
- `click` on shape to select
- draw shape on the canvas
- `double-click` (on the border of the fill) to add text
- `click`/`click&drag` elsewhere on the canvas to create another of the same shape

This way one could quickly create shape + text in quick succession and then point arrows from one shape to another.

**Comment by TodePond** [comment]
I understand now! Thank you for the detailed explanation + feedback.

I think this also relates to #3

In the gif I recorded, I pressed the 'v' key to change to the select-tool before double-clicking.
But some people have expressed that they would like to automatically go back into the select-tool after creating a shape.

**Comment by navakelvin** [comment]
> In the gif I recorded, I pressed the 'v' key to change to the select-tool before double-clicking. But some people have expressed that they would like to automatically go back into the select-tool after creating a shape.

That's right, OP tries to activate the text while the shape tool is still selected.

Perhaps something to consider would be https://github.com/tldraw/tldraw-beta/issues/40

**Comment by TodePond** [comment]
Thanks again for this request - we're currently exploring related to this. Let's do any further discussions in #3, unless you feel like there is something different here that should be discussed - let me know :)
