### ISSUE TITLE
[bug] Export to PNG - text no longer contained within rectangle

### ISSUE THREAD

**Issue by hopperrr** [tldraw/tldraw-beta#25]
![tldraw3](https://user-images.githubusercontent.com/10424330/207674848-7e6a815f-7a7b-4f8f-859d-a8e139790c74.jpg)

**Comment by TodePond** [comment]
Thanks! We've been working on some text improvements that should fix this! (we're hoping to push them out this week)

**Comment by TodePond** [comment]
This should be fixed now! 🎉
