### ISSUE TITLE
Pick a different font

### ISSUE THREAD

**Issue by nielsbom** [tldraw/tldraw-beta#26]
The original tldraw allows you to pick 1 of 4 fonts. The beta version does not (yet) allow this.

I saw [this comment](https://github.com/tldraw/tldraw-beta/issues/15#issuecomment-1348354315) by @TodePond that a font update is incoming.

Will that also introduce that feature?

Thanks for this awesome tool, btw! tldraw ftw

**Comment by TodePond** [comment]
Hey, thanks! This is a feature we're looking to bring across in some form.

Currently, we're planning to change to a new font in the new year, and we've been exploring which other fonts/variations would go well with it.

**Comment by steveruizok** [comment]
Yep! We're shipping with a new font for the draw style ([Shantell Sans](https://shantell-sans.arrowtype.com/)) as well as IBM Plex for serif / sans serif / monospace.

<img width="734" alt="Screen Shot 2023-01-06 at 4 42 53 PM" src="https://user-images.githubusercontent.com/23072548/211057410-d8533878-d4a0-4326-b3d4-4a7b316e0c32.png">

**Comment by nielsbom** [comment]
Thank you 🙏
