### ISSUE TITLE
Missing arrow body in exported png/svg

### ISSUE THREAD

**Issue by pdubroy** [tldraw/tldraw-beta#27]
I have a drawing on beta.tldraw.com that I'm trying to export as PNG, but in the exported file, the arrow bodies are missing:

https://user-images.githubusercontent.com/17293/208932571-c1b9cf3e-69c7-439c-b9fb-5a1e567ff9bb.mp4

This happens every time with these particular arrows, but I can't reproduce it with newly-drawn arrows on the same canvas. If I duplicate one of the "bad" arrows, the new arrow also doesn't export properly.

As a workaround, I can just delete and recreate the arrows. But let me know if there's any other info I can give you to help debug this.

**Comment by TodePond** [comment]
Thanks for the report! We've made some fixes to exporting that are coming out in the new year. Hopefully that will fix this too! :)

**Comment by AlexVipond** [comment]
I can reproduce by holding Shift to draw a perfectly vertical or horizontal arrow

**Comment by TodePond** [comment]
Thanks for the info folks! We've now fixed this internally and hope to push out the fix this week or next!

**Comment by TodePond** [comment]
This should be fixed on [beta.tldraw.com](https://beta.tldraw.com) now! Let me know if you still have issues with this :)
