### ISSUE TITLE
[Bug] Circles (shapes) with short text become large

### ISSUE THREAD

**Issue by juliusgb** [tldraw/tldraw-beta#28]
I can't make small circles with short text inside on beta but can make them on v1.
- When I make very small circles on beta, and write a number in there, it becomes elongatte (A). 
- When I resize it just a bit, it increases to B. 

On right-side is the v1 version: small circle with text inside works.

![SmallestCircle](https://user-images.githubusercontent.com/85777/210646092-107ff891-066e-4425-9de6-7158fa2bf2c5.PNG)

**Comment by juliusgb** [comment]
I heard there's a PR for this.

**Comment by TodePond** [comment]
Hey thanks for the report! We're working on a fix for this now

**Comment by TodePond** [comment]
This should work better now! Please do let me know if you have any more issues though :)
