### ISSUE TITLE
Return to SelectTool after tool usage?

### ISSUE THREAD

**Issue by evancloutier** [tldraw/tldraw-beta#3]
I've started using the beta a bit more and the main difference in UX that I've noticed is the persistence of tooling after a session or interaction has occurred.

In V1, the select tool is always resorted back to after a session completes (ie. drawing a shape!). In V2, said shape tool will instead persist to let more shapes be created. This may be a desired behaviour in V2, but I figured it is worth calling out as I think it is a major UX difference and requires some unlearning.

**Comment by judicaelandria** [comment]
Hey! yeah this has been asked many times on v1, perhaps that why it is implemented on v2 :)

**Comment by steveruizok** [comment]
Yeah, still considering a last minute change back to the behavior on v1. But we're leaving it like that for the moment.

**Comment by matlin** [comment]
I also prefer V1 behavior but, as a compromise, it would be nice to have `ESC` key map to  the select tool when another tool is selected. Excalidraw and Figma both use that pattern.

**Comment by alex-kim-dev** [comment]
I personally like Excalidraw's approach with the option to select the desired behavior:

![Screenshot from 2023-01-05 16-58-54](https://user-images.githubusercontent.com/45559664/210797357-b0165be6-eae3-4f2b-9307-b38e6f3c90bb.png)

**Comment by TodePond** [comment]
We're experimenting with some changes to this at the moment!

Thanks for all the feedback on this! There are even more people asking for it, eg: #40

**Comment by steveruizok** [comment]
Here's a preview PR where I've implemented this. Does it feel right to you? https://tldraw-lite-git-return-to-select-tldraw.vercel.app/

**Comment by judicaelandria** [comment]
hey @steveruizok can we add this to our preferences? because they're some people(including me) who want to keep the previously selected option

**Comment by TodePond** [comment]
Hey all, I've closed some related issues related to this - #23, #40 

There are some different options here that we're currently exploring!

**Comment by TodePond** [comment]
We're trying out some changes on https://beta.tldraw.com
Let us know how it goes, and what you think! :)

**Comment by judicaelandria** [comment]
that should do it! but the lock icon is too small 😅

**Comment by nielsbom** [comment]
I just learned about the lock feature, looks good, and yes a bit small. 

I think doing a double-click (as v1 apparently had) to temporarily put the lock on just the tool you clicked has a good flow too. I do wonder about the accessibility of double-clicking. A short search did not give any negative indicators, but I'm no expert.

I can imagine how some people would always want the global-lock on and others would always want it off. So maybe this should be something in the preferences instead of in the panel-UI. But I'm just one user so 🤷

**Comment by TodePond** [comment]
As this is now the default behaviour, I'll close this issue now. This could be revisited again in the future though!
