### ISSUE TITLE
All text has max width and can't be resized

### ISSUE THREAD

**Issue by TheMapSmith** [tldraw/tldraw-beta#30]
I ran into an odd issue with a new board this morning. For a while, I was able to create text as usual. 

Then, for some reason, my text will only go to a certain width and can't be any wider. 

Additionally, text that was originally created gets shrunk when it is duplicated. 

![tldraw](https://user-images.githubusercontent.com/8357118/211832929-b2031f22-d1ef-4ac7-88d7-3e4258325bdc.gif)

This is happening across multiple boards on my machine this morning.

**Comment by TheMapSmith** [comment]
Update! I completely exited out of Chrome and got back in and things were back to normal... for a minute. Then I zeroed in on the issue! 

**Reproduce:**
1. Create a shape
2. Double-click on the shape to place text in the middle 
3. Create a new free text object 

**Result:** 
* That new text object will have a max width that matches the shape 
* All new text across all boards in the browser will be stuck to that max width 


![tldraw-bug](https://user-images.githubusercontent.com/8357118/211834967-07580d28-9c55-4676-bee5-1df3e1a2c040.gif)

**Comment by TodePond** [comment]
Thank you, we've been tracking this one - so you're reproducible steps are very useful! We're working on a fix today that should come out in the next release.

**Comment by TodePond** [comment]
This should be fixed now!
