### ISSUE TITLE
[Feature] When creating an object bounding box should remain on newly created element?

### ISSUE THREAD

**Issue by webjoyable** [tldraw/tldraw-beta#33]
Wouldn't it be useful if the bounding box automatically appears on the newly created element? We have to select every element manually after it's been created in order to resize/reshape it. At least somewhere should be a toggle option for this feature to be enabled or disabled.

**Comment by TodePond** [comment]
Thanks for the feedback! It's helpful to hear that - quite a few people have mentioned the same thing, so I agree there should *at least* be an option for this.

Related: #3
