### ISSUE TITLE
[bug] The beta version does not show the pasted images, only their box

### ISSUE THREAD

**Issue by navakelvin** [tldraw/tldraw-beta#37]
Hello creator,

The beta version does not show the images, only its box. To reproduce, simply copy and paste an image into a project in beta.

![image](https://user-images.githubusercontent.com/77164639/209035087-811923e3-57b0-4044-96b9-5d677b140220.png)

However, when you export it in a image format, pasted images are displayed.

**Comment by TodePond** [comment]
Hey sorry, I missed this one! Is this still an issue?

**Comment by navakelvin** [comment]
Yes sir, i clear cache and cookies before testing on chrome, edge and opera and it still persists.

It only happens in Beta, in the old / normal version, the images are displayed normally.

**Comment by TodePond** [comment]
We've been looking into this issue, and we think we've found the cause! We're working on it now :)

**Comment by navakelvin** [comment]
Something great to hear guys :)

**Comment by TodePond** [comment]
Just checking in on this one - is this still not working for you?

**Comment by navakelvin** [comment]
Its working now, thanks for that!
