### ISSUE TITLE
[Feature] Select shape after create

### ISSUE THREAD

**Issue by navakelvin** [tldraw/tldraw-beta#40]
Hi guys, one improvements here that you could consider.

- [ ] When creating an arrow/shape, it is automatically selected showing its modification nodes.
  -  You could set a toggle in the "Select after create" preferences.

:)

**Comment by TodePond** [comment]
Thanks for the request! I think this falls under this issue? #3

**Comment by steveruizok** [comment]
Here's a preview PR where I've implemented this. Does it feel right to you? https://tldraw-lite-git-return-to-select-tldraw.vercel.app/

**Comment by TodePond** [comment]
As there are a few issues about this - I'm marking this one as a duplicate, and we can carry on the discussion here: #3
