### ISSUE TITLE
[Feature] Unlimited Pages or increased number of pages

### ISSUE THREAD

**Issue by VelvetThunder1** [tldraw/tldraw-beta#42]
It would be useful to have an increased number of pages, or at least be able to customize the limit. Alternatively, if anyone can help me find the code which determines the maximum number of pages and how to edit it, that would be very helpful.

**Comment by TodePond** [comment]
The max number of pages is currently 20 on https://beta.tldraw.com
Is that too low for your needs? As a short-term fix, feel free to make extra multiplayer rooms if you need more space :)

**Comment by VelvetThunder1** [comment]
Sorry, but since I'm not too familiar with tldraw, I'm not sure what you mean by "extra multiplayer rooms." I'd appreciate it if you could elaborate.

**Comment by VelvetThunder1** [comment]
Also, it appears that on https://www.tldraw.com, that there isn't a page limit as I have created 40 and haven't reached the max, is that the case?

**Comment by TodePond** [comment]
> Sorry, but since I'm not too familiar with tldraw, I'm not sure what you mean by "extra multiplayer rooms." I'd appreciate it if you could elaborate.

No problem! :)

What I mean is this:
When you're on https://beta.tldraw.com you can click the 'Share' button in the top-right to make a shared project. You can make as many of these as you want!

Inside each shared project you can currently have 20 'pages'.
But you can make as many projects if you want!

Multiple people have asked for more pages though, so we're considering increasing the page limit too

> Also, it appears that on https://www.tldraw.com/, that there isn't a page limit as I have created 40 and haven't reached the max, is that the case?

I'm not sure about the page limit in v1. @steveruizok can you confirm if there's a page limit in v1?

**Comment by VelvetThunder1** [comment]
> What I mean is this: When you're on https://beta.tldraw.com you can click the 'Share' button in the top-right to make a shared project. You can make as many of these as you want!
> 
> Inside each shared project you can currently have 20 'pages'. But you can make as many projects if you want!
I understand now, thank you for clarifying. I'll close the issue now, thanks again.
