### ISSUE TITLE
Can you add Thai langauge ?

### ISSUE THREAD

**Issue by watchakorn-18k** [tldraw/tldraw-beta#43]
Or where can I help you with Thai translation for this beta version?

**Comment by TodePond** [comment]
Hello! We are missing quite a lot of translations at the moment, including Thai. We are hoping to add them this year. If you would like to contribute, that would be very helpful! But only if you'd like to :)

These are all of the translation strings currently. Any that you fill out would be great!
https://gist.github.com/TodePond/06b32cac18b9dfcf3f5edead6ee3bcd8

**Comment by watchakorn-18k** [comment]
Mr. @TodePond, how can I file the string after translating?

**Comment by TodePond** [comment]
Hello! I see that you have submitted a PR on the examples repo (https://github.com/tldraw/tldraw-examples)
Thank you very much! I will use it to add support for Thai in the tldraw package.

We are currently working on creating a system where community members can suggest translation changes in an easier way. But for now, you are welcome to send them to me here, or on our discord (https://discord.gg/qtSWaVv6jy).
