### ISSUE TITLE
unable to group shape with another grouped shape

### ISSUE THREAD

**Issue by judicaelandria** [tldraw/tldraw-beta#5]
https://user-images.githubusercontent.com/46365844/204238450-e901b471-7a06-4a71-9ea4-f8228b8b0ab3.mov

can't give you the tldraw file because the file menu is not present

**Comment by steveruizok** [comment]
Can reproduce:
1. Create three geo shapes, A B and C
2. Draw an arrow from A to B
3. Select B and C
4. Group B and C (creating group G1)
5. Select G1 + the arrow
6. Group the current selection

Expected
A new group would exist containing the arrow and the G1

Observed
No new group is created

<img width="589" alt="image" src="https://user-images.githubusercontent.com/23072548/205454137-7498acd9-27da-4a78-8001-1d7f6ea6aa80.png">

**Comment by steveruizok** [comment]
(This may be intended behavior due to the weirdness of having arrows in groups without their bound shapes.)
