### ISSUE TITLE
Open tldraw-beta projects in tldraw

### ISSUE THREAD

**Issue by two9seven** [tldraw/tldraw-beta#60]
I started a board on the beta version on accident and would like to use the old version because it can send readonly links. Unless there is a way to share readonly on the beta. Thanks for your help.

**Comment by TodePond** [comment]
Sorry there's no way to convert a beta version -> old version.

We are currently working on readonly links though! It should hopefully come out in the next few weeks.

**Comment by TodePond** [comment]
Hey, read-only links are now here! 

![2023-02-23 at 17 08 21 - Silver Junglefowl](https://user-images.githubusercontent.com/15892272/221148819-38655f3c-f527-4303-a339-f9ce6ca833e9.gif)
