### ISSUE TITLE
Text Alignment does not seem to do anything

### ISSUE THREAD

**Issue by trusz** [tldraw/tldraw-beta#7]
The text is always centered regardless of its setting

<details>
  <summary>Example file</summary>
  <pre>
{
    "shapes": [
        {
            "x": 0.29491460125234426,
            "y": -345.5603412935589,
            "rotation": 0,
            "id": "shape:YvhcYRPOxzC6DG39RZSty",
            "index": "a1",
            "type": "geo",
            "props": {
                "w": 259.70508539874766,
                "h": 95.5603412935589,
                "geo": "rectangle",
                "color": "red",
                "fill": "semi",
                "dash": "solid",
                "size": "s",
                "opacity": "1",
                "font": "draw",
                "text": "Left",
                "align": "start",
                "growY": 0
            },
            "parentId": "page:Y71oOJhEZGD4_0Qqi06ZJ",
            "typeName": "shape"
        },
        {
            "x": 270,
            "y": -345.5603412935589,
            "rotation": 0,
            "id": "shape:iePSorBBbMNMN0kL6XRMW",
            "index": "a2",
            "type": "geo",
            "props": {
                "w": 259.70508539874766,
                "h": 95.5603412935589,
                "geo": "rectangle",
                "color": "red",
                "fill": "semi",
                "dash": "solid",
                "size": "s",
                "opacity": "1",
                "font": "draw",
                "text": "Center",
                "align": "end",
                "growY": 0
            },
            "parentId": "page:Y71oOJhEZGD4_0Qqi06ZJ",
            "typeName": "shape"
        },
        {
            "x": 539.7050853987477,
            "y": -345.5603412935589,
            "rotation": 0,
            "id": "shape:ME7x85WpuTidScOtmhoYz",
            "index": "a3",
            "type": "geo",
            "props": {
                "w": 259.70508539874766,
                "h": 95.5603412935589,
                "geo": "rectangle",
                "color": "red",
                "fill": "semi",
                "dash": "solid",
                "size": "s",
                "opacity": "1",
                "font": "draw",
                "text": "Right",
                "align": "end",
                "growY": 0
            },
            "parentId": "page:Y71oOJhEZGD4_0Qqi06ZJ",
            "typeName": "shape"
        }
    ],
    "rootShapeIds": [
        "shape:YvhcYRPOxzC6DG39RZSty",
        "shape:iePSorBBbMNMN0kL6XRMW",
        "shape:ME7x85WpuTidScOtmhoYz"
    ]
}
  </pre>
</details>

Example image:
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/1510715/205165815-73927a2b-658f-477f-b3e8-661e5a203848.png">

**Comment by steveruizok** [comment]
Ah with only one line it won't really have an effect. Multiline text will show the difference though. 

<img width="849" alt="image" src="https://user-images.githubusercontent.com/23072548/205453937-1d372859-b181-4fa3-a6af-8fabe8aab8d8.png">
