### ISSUE TITLE
Arrow Texts cannot have monospace font style

### ISSUE THREAD

**Issue by pouyakary** [tldraw/tldraw-beta#77]
As you can see below, the font style of the arrow is set to monospace but it renders it to the fallback font:

<img width="536" alt="Screenshot 1402-01-25 at 2 52 54 AM" src="https://user-images.githubusercontent.com/2157285/231903768-aca83768-9b60-464e-b570-3a7514dc49ca.png">

I'm experiencing this in the version v2.0.3 of the extension for the VS Code.

**Comment by TodePond** [comment]
Hi, thanks for the report!

**Comment by TodePond** [comment]
Hey we've fixed this internally now, and it should get released next week.
You can test it out before then at https://staging.tldraw.com/

**Comment by pouyakary** [comment]
@TodePond thanks a lot !
