### ISSUE TITLE
Blank screen, stuck on Loading.

### ISSUE THREAD

**Issue by al1gned** [tldraw/tldraw-beta#79]
Using the new vscode extension. 

https://user-images.githubusercontent.com/59787884/232123594-5ae6897a-82a3-478e-9d16-92c77b139bf9.mp4

**Comment by adamddurrant** [comment]
I'm getting the same

**Comment by TodePond** [comment]
Thanks for the report!

**Comment by al1gned** [comment]
> Hey! We just published a new version of the extension (version 2.0.4). Could you give it a try and let us know if it now works for you? 🤞

Thanks, it's working now!

**Comment by MitjaBezensek** [comment]
So great to hear that! Thanks for reporting it!
