### ISSUE TITLE
[bug] Selection criteria for Selection tool

### ISSUE THREAD

**Issue by sedghi** [tldraw/tldraw-beta#8]
The criteria for selection is "if the selection area touches even one pixel of the object it gets selected", and it is inconsistent with some other apps like Inkscape which there it is "if the selection area include all the pixels of the object"

Can we have an option at least that we can specify which selection rule the app would work with? 

To me, the latter seems to have a lot of usecases for overlapping objects. 

On a separate note, Selection tool keyboard shortcut is set to "V", is there any reason why it is not "S"? (similar to other tools which is basically the first letter?)

Thanks

**Comment by steveruizok** [comment]
You can hold control or command for the alternative selection mode. By default it selects anything the selection box is touching, but in the alt mode it selects only shapes that are entirely contained in the box.

We may bring the "swap default selection mode" feature up from the v1 project as a preference, depending on demand!
